language: shell
os: linux
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
env:
 matrix:
   - FAIL=1
   - FAIL=0
script:
 - while sleep 5; do echo .; done  # Cheap wait command
 - if [[ $FAIL == 1 ]] ; then false ; else true ; fi  # Cheap test command
